language: php
php:
  - "5.4"
before_install:
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
before_script:
  - composer install
  - composer selfupdate
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover